import Image from 'next/image';
import { BookOpen, Mic, PictureInPicture, PlayCircle } from 'lucide-react';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { Button } from '@/components/ui/button';

// Mock data
const simplifiedCurriculum = {
  title: 'Solar System 101',
  simplifiedContent: 'Our solar system has a big star called the Sun. Many planets go around the Sun. Earth is one of them. It is our home.',
  childFriendlyDescription: 'Let\'s go on a trip to space! We will see the big, bright Sun and our beautiful home, planet Earth.',
  visuals: [
    { id: '1', url: PlaceHolderImages.find(p => p.id === 'curriculum-review-1')?.imageUrl || '', hint: 'solar system'},
  ],
  audioUrl: '/audio/placeholder.mp3'
};

export default function CurriculumReviewPage({ params }: { params: { curriculumId: string } }) {
  return (
    <>
      <h1 className="text-lg font-semibold md:text-2xl font-headline">
        Review: {simplifiedCurriculum.title}
      </h1>
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-primary" />
                Simplified Content
              </CardTitle>
              <CardDescription>
                This is the simplified text generated by the AI for students.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-bold text-lg">Child-Friendly Description</h3>
                <p className="text-muted-foreground">{simplifiedCurriculum.childFriendlyDescription}</p>
              </div>
              <div>
                <h3 className="font-bold text-lg">Core Concepts</h3>
                <p className="text-muted-foreground leading-relaxed">{simplifiedCurriculum.simplifiedContent}</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Mic className="w-5 h-5 text-primary" />
                Audio Narration
              </CardTitle>
              <CardDescription>
                Listen to the generated audio that will be played during the lesson.
              </CardDescription>
            </CardHeader>
            <CardContent>
                <div className="flex items-center gap-4 p-4 bg-muted rounded-lg">
                    <Button variant="outline" size="icon">
                        <PlayCircle className="w-6 h-6"/>
                    </Button>
                    <div className="w-full bg-border rounded-full h-2">
                        <div className="bg-primary h-2 rounded-full w-1/3"></div>
                    </div>
                    <span className="text-sm text-muted-foreground">0:12 / 0:35</span>
                </div>
            </CardContent>
          </Card>
        </div>
        
        <div className="space-y-6">
            <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <PictureInPicture className="w-5 h-5 text-primary" />
                Generated Visuals
              </CardTitle>
              <CardDescription>
                These images were created by AI to accompany the lesson.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-1 gap-4">
                {simplifiedCurriculum.visuals.map(visual => (
                  <div key={visual.id} className="aspect-video w-full relative overflow-hidden rounded-lg">
                    <Image
                      src={visual.url}
                      alt="Generated visual"
                      fill
                      className="object-cover"
                      data-ai-hint={visual.hint}
                    />
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

      </div>
    </>
  );
}
